local cli = require("vimgentic.pi.cli")
local config = require("vimgentic.config")
local root = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h:h")

describe("vimgentic.pi.cli pairing", function()
  it("does not add pairing guidance unless the user enables it", function()
    config.setup()
    eq({ "pi", "--tui-mode", "fullscreen", "--session-id", "id", "--extension", root .. "/pi/session-log.js" }, cli.interactive({ session_id = "id" }))
    eq({ "pi", "--mode", "rpc" }, cli.build())
  end)

  it("loads the bundled guidance for new and resumed native chat sessions", function()
    config.setup({ pi = { command = "/tmp/pi-launch" }, pairing = { enabled = true } })
    local fresh = cli.interactive({ session_id = "new-session" })
    local resumed = cli.interactive({ session_path = "/tmp/session.jsonl" })
    local rpc = cli.build()
    config.setup()
    eq({ "/tmp/pi-launch", "--tui-mode", "fullscreen", "--session-id", "new-session", "--extension", root .. "/pi/session-log.js", "--extension", root .. "/pi/pairing.js" }, fresh)
    eq({ "/tmp/pi-launch", "--tui-mode", "fullscreen", "--session", "/tmp/session.jsonl", "--extension", root .. "/pi/session-log.js", "--extension", root .. "/pi/pairing.js" }, resumed)
    eq({ "/tmp/pi-launch", "--mode", "rpc" }, rpc)
    eq("file", assert(vim.uv.fs_stat(root .. "/pi/pairing.js")).type)
    eq("file", assert(vim.uv.fs_stat(root .. "/pi/session-log.js")).type)
  end)

  it("passes a tool allowlist only to the requested operation", function()
    eq({ "pi", "--mode", "rpc", "--tools", "read,grep,find,ls" }, cli.build({ tools = { "read", "grep", "find", "ls" } }))
    eq({ "pi", "--mode", "rpc" }, cli.build())
    eq({ "pi", "--tui-mode", "fullscreen", "--extension", root .. "/pi/session-log.js" }, cli.interactive())
  end)

  it("rejects a non-boolean pairing option", function()
    local ok, error_message = pcall(config.setup, { pairing = { enabled = "yes" } })
    config.setup()
    eq(false, ok)
    truthy(error_message:find("vimgentic: pairing.enabled must be a boolean", 1, true))
  end)
end)
