local replacement = require("vimgentic.ui.replacement")
local selection = require("vimgentic.selection")

local function fixture(lines, first, last)
  local buffer = vim.api.nvim_create_buf(true, false)
  vim.api.nvim_set_current_buf(buffer)
  vim.api.nvim_buf_set_lines(buffer, 0, -1, false, lines)
  local preview = replacement.capture(assert(selection.capture({ first = first, last = last })))
  return buffer, preview
end

local function cleanup(buffer, preview)
  preview:discard()
  if vim.api.nvim_buf_is_valid(buffer) then
    vim.api.nvim_buf_delete(buffer, { force = true })
  end
end

describe("vimgentic.ui.replacement", function()
  it("keeps the source and editor focus unchanged until the user opens and accepts the preview", function()
    local original = { "local tax = 1", "return price + tax", "-- keep" }
    local buffer, preview = fixture(original, 2, 2)
    local editor_window = vim.api.nvim_get_current_win()
    truthy(preview:propose("return price * tax"))
    eq(editor_window, vim.api.nvim_get_current_win())
    eq(original, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    truthy(preview:open())
    eq("diff", vim.bo[preview.buffer].filetype)
    eq(false, vim.bo[preview.buffer].modifiable)
    local diff = table.concat(vim.api.nvim_buf_get_lines(preview.buffer, 0, -1, false), "\n")
    truthy(diff:find("-return price + tax", 1, true))
    truthy(diff:find("+return price * tax", 1, true))
    eq(original, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    truthy(preview:accept())
    eq({ "local tax = 1", "return price * tax", "-- keep" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    eq(editor_window, vim.api.nvim_get_current_win())
    eq(false, vim.api.nvim_buf_is_valid(preview.buffer))
    eq(false, preview:accept())
    cleanup(buffer, preview)
  end)

  it("discards a preview without changing the source", function()
    local buffer, preview = fixture({ "return price" }, 1, 1)
    truthy(preview:propose("return total"))
    truthy(preview:open())
    preview:discard()
    eq({ "return price" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    eq(false, preview:accept())
    eq(false, preview:open())
    cleanup(buffer, preview)
  end)

  it("tracks the original range past insertions at both boundaries", function()
    local buffer, preview = fixture({ "before", "old", "after" }, 2, 2)
    truthy(preview:propose("new\nextra"))
    vim.api.nvim_buf_set_lines(buffer, 1, 1, false, { "inserted before" })
    vim.api.nvim_buf_set_lines(buffer, 3, 3, false, { "inserted after" })
    truthy(preview:accept())
    eq({ "before", "inserted before", "new", "extra", "inserted after", "after" },
      vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    cleanup(buffer, preview)
  end)

  it("makes acceptance one undoable buffer change", function()
    local buffer = vim.api.nvim_create_buf(true, false)
    vim.api.nvim_set_current_buf(buffer)
    local undo_levels = vim.bo[buffer].undolevels
    vim.bo[buffer].undolevels = -1
    vim.api.nvim_buf_set_lines(buffer, 0, -1, false, { "before", "old", "after" })
    vim.bo[buffer].undolevels = undo_levels
    local preview = replacement.capture(assert(selection.capture({ first = 2, last = 2 })))
    truthy(preview:propose("new"))
    truthy(preview:accept())
    eq({ "before", "new", "after" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    vim.cmd("undo")
    eq({ "before", "old", "after" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    cleanup(buffer, preview)
  end)

  it("rejects edits inside the selection after the preview opens", function()
    local buffer, preview = fixture({ "before", "local total = price", "after" }, 2, 2)
    truthy(preview:propose("local total = price + tax"))
    truthy(preview:open())
    vim.api.nvim_buf_set_text(buffer, 1, 14, 1, 19, { "discounted_price" })
    local applied, error_message = preview:accept()
    eq(false, applied)
    eq("The selected text changed; no text was replaced. Request a new replacement.", error_message)
    eq({ "before", "local total = discounted_price", "after" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    cleanup(buffer, preview)
  end)

  it("rejects new lines inside the selection", function()
    local buffer, preview = fixture({ "before", "one", "two", "after" }, 2, 3)
    truthy(preview:propose("replacement"))
    vim.api.nvim_buf_set_lines(buffer, 2, 2, false, { "user addition" })
    eq(false, preview:accept())
    eq({ "before", "one", "user addition", "two", "after" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    cleanup(buffer, preview)
  end)

  it("rejects a deleted range even when identical text is inserted at its old position", function()
    local buffer, preview = fixture({ "before", "old", "after" }, 2, 2)
    truthy(preview:propose("new"))
    vim.api.nvim_buf_set_lines(buffer, 1, 2, false, {})
    vim.api.nvim_buf_set_lines(buffer, 1, 1, false, { "old" })
    local applied, error_message = preview:accept()
    eq(false, applied)
    eq("The selected range no longer exists; no text was replaced", error_message)
    eq({ "before", "old", "after" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    cleanup(buffer, preview)
  end)

  it("rejects a renamed source buffer", function()
    local buffer, preview = fixture({ "old" }, 1, 1)
    truthy(preview:propose("new"))
    vim.api.nvim_buf_set_name(buffer, "/tmp/renamed-source.lua")
    local applied, error_message = preview:accept()
    eq(false, applied)
    eq("The source buffer changed its name; no text was replaced", error_message)
    eq({ "old" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    cleanup(buffer, preview)
  end)

  it("rejects readonly and unmodifiable source buffers", function()
    local buffer, preview = fixture({ "old" }, 1, 1)
    truthy(preview:propose("new"))
    vim.bo[buffer].readonly = true
    eq(false, preview:accept())
    vim.bo[buffer].readonly = false
    vim.bo[buffer].modifiable = false
    local applied, error_message = preview:accept()
    eq(false, applied)
    eq("The source buffer is not writable; no text was replaced", error_message)
    eq({ "old" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    cleanup(buffer, preview)
  end)

  it("discards a pending result when the source buffer is deleted", function()
    local buffer, preview = fixture({ "old" }, 1, 1)
    vim.api.nvim_buf_delete(buffer, { force = true })
    eq(false, preview:propose("new"))
    eq(false, preview:open())
    eq(false, preview:accept())
    cleanup(buffer, preview)
  end)

  it("discards unchanged replacements without opening a preview", function()
    local buffer, preview = fixture({ "old" }, 1, 1)
    local ready, message = preview:propose("old")
    eq(false, ready)
    eq("Pi returned unchanged code; no text was replaced", message)
    eq(false, preview:open())
    eq({ "old" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    cleanup(buffer, preview)
  end)

  it("discards the replacement when the user closes its preview window", function()
    local buffer, preview = fixture({ "old" }, 1, 1)
    truthy(preview:propose("new"))
    truthy(preview:open())
    vim.api.nvim_win_close(preview.window, true)
    eq(false, preview:accept())
    eq({ "old" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    cleanup(buffer, preview)
  end)
end)
