local selection = require("vimgentic.selection")

local function source(lines)
  local buffer = vim.api.nvim_create_buf(true, false)
  vim.api.nvim_set_current_buf(buffer)
  vim.api.nvim_buf_set_lines(buffer, 0, -1, false, lines)
  vim.bo[buffer].filetype = "lua"
  return buffer
end

describe("vimgentic.selection", function()
  it("captures unsaved lines and renders their file and range", function()
    local buffer = source({ "local tax = 1", "local total = price + tax", "return total" })
    vim.api.nvim_buf_set_name(buffer, "/tmp/project/total.lua")
    local context = assert(selection.capture({ first = 2, last = 3 }))
    eq({ "local total = price + tax", "return total" }, context.lines)
    truthy(context.modified)
    local rendered = selection.render(context)
    truthy(rendered:find("/tmp/project/total.lua", 1, true))
    truthy(rendered:find("Lines: 2-3", 1, true))
    truthy(rendered:find("unsaved changes", 1, true))
    truthy(rendered:find("```lua\nlocal total = price + tax\nreturn total\n```", 1, true))
    vim.api.nvim_buf_delete(buffer, { force = true })
  end)

  it("captures the current visual selection instead of older visual marks", function()
    local buffer = source({ "one", "two", "three", "four", "five", "six", "seven" })
    vim.api.nvim_buf_set_mark(buffer, "<", 1, 0, {})
    vim.api.nvim_buf_set_mark(buffer, ">", 2, 0, {})
    vim.cmd("normal! 7GV5G")
    eq("V", vim.fn.mode())
    local context = assert(selection.capture({ visual = true }))
    eq({ "five", "six", "seven" }, context.lines)
    eq(5, context.first)
    eq(7, context.last)
    vim.cmd("normal! \27")
    vim.api.nvim_buf_delete(buffer, { force = true })
  end)

  it("uses visual marks after visual mode ends", function()
    local buffer = source({ "one", "two", "three" })
    vim.api.nvim_buf_set_mark(buffer, "<", 2, 0, {})
    vim.api.nvim_buf_set_mark(buffer, ">", 3, 0, {})
    local context = assert(selection.capture({ visual = true }))
    eq({ "two", "three" }, context.lines)
    vim.api.nvim_buf_delete(buffer, { force = true })
  end)

  it("captures at most twenty neighbouring lines on each side of the cursor", function()
    local lines = {}
    for index = 1, 80 do lines[index] = "line " .. index end
    local buffer = source(lines)
    vim.api.nvim_win_set_cursor(0, { 40, 0 })
    local context = assert(selection.capture())
    eq(20, context.first)
    eq(60, context.last)
    eq(vim.list_slice(lines, 20, 60), context.lines)
    vim.api.nvim_buf_delete(buffer, { force = true })
  end)

  it("keeps embedded code fences inside an unnamed buffer's source block", function()
    local buffer = source({ "```lua", "return 1", "```" })
    vim.bo[buffer].modified = false
    local rendered = selection.render(assert(selection.capture()))
    truthy(rendered:find("File: [No Name]\nLines: 1-3\nSource: live buffer.", 1, true))
    truthy(rendered:find("````lua\n```lua\nreturn 1\n```\n````", 1, true))
    vim.api.nvim_buf_delete(buffer, { force = true })
  end)

  it("rejects missing ranges and non-source buffers without reading their contents", function()
    local buffer = source({ "one" })
    local context, error_message = selection.capture({ first = 0, last = 1 })
    eq(nil, context)
    eq("The selected range no longer exists", error_message)
    context, error_message = selection.capture({ first = 1, last = 2 })
    eq(nil, context)
    eq("The selected range no longer exists", error_message)
    vim.bo[buffer].buftype = "nofile"
    context, error_message = selection.capture()
    eq(nil, context)
    eq("Vimgentic needs a source buffer", error_message)
    vim.api.nvim_buf_delete(buffer, { force = true })
    context, error_message = selection.capture({ buffer = buffer })
    eq(nil, context)
    eq("Vimgentic needs a source buffer", error_message)
  end)
end)
