local status = require("vimgentic.ui.status")

describe("vimgentic.ui.status", function()
  it("stops one range without removing another request's range or activity", function()
    local buffer = vim.api.nvim_create_buf(true, false)
    vim.api.nvim_buf_set_lines(buffer, 0, -1, false, { "one", "two", "three", "four" })
    local first = status.range(buffer, 1, 1)
    local second = status.range(buffer, 3, 4)
    first:stop()
    second:set_activity("read neighbour.lua")
    local start_row, end_row = second:get_range()
    eq(2, start_row)
    eq(4, end_row)
    second:stop()
    eq(nil, second:get_range())
    vim.api.nvim_buf_delete(buffer, { force = true })
  end)
end)
