local tour = require("vimgentic.ui.tour")
local util = require("vimgentic.util")
local namespace = vim.api.nvim_create_namespace("vimgentic.tour")

local function text(buffer)
  return table.concat(vim.api.nvim_buf_get_lines(buffer, 0, -1, false), "\n")
end

local function press(key)
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes(key, true, false, true), "xt", false)
end

local function marks(buffer)
  return vim.api.nvim_buf_get_extmarks(buffer, namespace, 0, -1, { details = true })
end

local function panel_window(buffer)
  for _, window in ipairs(vim.api.nvim_tabpage_list_wins(0)) do
    if vim.api.nvim_win_get_buf(window) == buffer then return window end
  end
end

local function fixture(callback)
  vim.cmd("stopinsert")
  local directory = vim.fn.tempname()
  vim.fn.mkdir(directory, "p")
  directory = assert(vim.uv.fs_realpath(directory))
  vim.fn.writefile({ "entry", "call()", "continue()", "done" }, directory .. "/z.lua")
  vim.fn.writefile({ "callee", "return total", "end" }, directory .. "/a.lua")
  local original_notify = util.notify
  local notices = {}
  util.notify = function(message) table.insert(notices, message) end
  vim.cmd("tabnew")
  local tab = vim.api.nvim_get_current_tabpage()
  vim.cmd.edit(vim.fn.fnameescape(directory .. "/z.lua"))
  local result = {
    kind = "tour", cwd = directory, prompt = "Trace the request", report = "# Request flow\nThe caller delegates, then finishes.",
    locations = {
      { path = directory .. "/z.lua", lnum = 2, col = 1, count = 2, notes = "The caller starts the work.\nThese two lines dispatch the request.", source = "working tree", anchor = "call()" },
      { path = directory .. "/a.lua", lnum = 2, col = 8, count = 1, notes = "The callee returns the total.", source = "working tree", anchor = "return total" },
      { path = directory .. "/z.lua", lnum = 4, col = 1, count = 1, notes = "The caller finishes the request.", source = "working tree", anchor = "done" },
    },
  }
  local ok, error_message = xpcall(function() callback(result, notices) end, debug.traceback)
  if vim.api.nvim_tabpage_is_valid(tab) then
    vim.api.nvim_set_current_tabpage(tab)
    tour.close()
    vim.cmd("tabclose!")
  end
  for _, buffer in ipairs(vim.api.nvim_list_bufs()) do
    if vim.api.nvim_buf_get_name(buffer):find(directory, 1, true) == 1 then
      vim.api.nvim_buf_delete(buffer, { force = true })
    end
  end
  util.notify = original_notify
  vim.fn.delete(directory, "rf")
  assert(ok, error_message)
end

describe("vimgentic.ui.tour player", function()
  it("opening starts on the first code range with only that step's explanation beside it", function()
    fixture(function(result, notices)
      local editor, source = vim.api.nvim_get_current_win(), vim.api.nvim_get_current_buf()
      local panel = tour.open(result)
      eq(editor, vim.api.nvim_get_current_win())
      eq({ 2, 0 }, vim.api.nvim_win_get_cursor(editor))
      truthy(vim.api.nvim_win_get_position(panel_window(panel))[2] > vim.api.nvim_win_get_position(editor)[2])
      truthy(text(panel):find("Step 1 of 3", 1, true))
      truthy(text(panel):find(result.locations[1].notes, 1, true))
      eq(nil, text(panel):find(result.locations[2].notes, 1, true))
      eq(false, vim.bo[panel].modifiable)
      eq(false, vim.bo[source].modified)
      local highlight = marks(source)[1]
      eq(1, highlight[2])
      eq(3, highlight[4].end_row)
      eq("VimgenticTourRange", highlight[4].hl_group)
      eq({}, notices)
    end)
  end)

  it("actual arrow keys walk across files and back while the side explanation follows each range", function()
    fixture(function(result, notices)
      local editor, first_buffer = vim.api.nvim_get_current_win(), vim.api.nvim_get_current_buf()
      local panel = tour.open(result)
      press("<Right>")
      eq(editor, vim.api.nvim_get_current_win())
      eq(result.locations[2].path, vim.api.nvim_buf_get_name(0))
      eq({ 2, 7 }, vim.api.nvim_win_get_cursor(0))
      truthy(text(panel):find("Step 2 of 3", 1, true))
      truthy(text(panel):find(result.locations[2].notes, 1, true))
      eq(nil, text(panel):find(result.locations[1].notes, 1, true))
      eq({}, marks(first_buffer))
      local second_buffer = vim.api.nvim_get_current_buf()
      press("<Right>")
      eq(result.locations[3].path, vim.api.nvim_buf_get_name(0))
      eq({ 4, 0 }, vim.api.nvim_win_get_cursor(0))
      truthy(text(panel):find("End of tour. Press Esc to exit.", 1, true))
      eq({}, marks(second_buffer))
      press("<Left>")
      eq(result.locations[2].path, vim.api.nvim_buf_get_name(0))
      truthy(text(panel):find("Step 2 of 3", 1, true))
      eq({}, notices)
    end)
  end)

  it("the tour keeps the chosen editor even when another source window is larger", function()
    fixture(function(result)
      local chosen = vim.api.nvim_get_current_win()
      vim.cmd("vsplit")
      local other = vim.api.nvim_get_current_win()
      vim.api.nvim_win_set_width(chosen, 20)
      vim.api.nvim_set_current_win(chosen)
      local other_buffer = vim.api.nvim_win_get_buf(other)
      tour.open(result)
      press("<Right>")
      eq(chosen, vim.api.nvim_get_current_win())
      eq(result.locations[2].path, vim.api.nvim_buf_get_name(0))
      eq(other_buffer, vim.api.nvim_win_get_buf(other))
    end)
  end)

  it("panel arrows advance the source and overview remains available without mixing stop explanations", function()
    fixture(function(result)
      local editor = vim.api.nvim_get_current_win()
      local panel = tour.open(result)
      vim.api.nvim_set_current_win(panel_window(panel))
      press("g?")
      truthy(text(panel):find(result.report, 1, true))
      press("<Right>")
      eq(editor, vim.api.nvim_get_current_win())
      truthy(text(panel):find(result.locations[2].notes, 1, true))
      eq(nil, text(panel):find(result.report, 1, true))
    end)
  end)

  it("Escape removes the highlight and restores previous buffer mappings including expression callbacks", function()
    fixture(function(result)
      local buffer = vim.api.nvim_get_current_buf()
      local left = function() return "h" end
      vim.keymap.set("n", "<Left>", left, { buffer = buffer, expr = true, silent = true, nowait = true, desc = "Original left" })
      vim.keymap.set("n", "<Right>", "l", { buffer = buffer, remap = true, desc = "Original right" })
      local before_left = vim.fn.maparg("<Left>", "n", false, true)
      local before_right = vim.fn.maparg("<Right>", "n", false, true)
      local before_escape = vim.fn.maparg("<Esc>", "n", false, true)
      local panel = tour.open(result)
      press("<Esc>")
      eq(false, vim.api.nvim_buf_is_valid(panel))
      eq({}, marks(buffer))
      eq(before_left, vim.fn.maparg("<Left>", "n", false, true))
      eq(before_right, vim.fn.maparg("<Right>", "n", false, true))
      eq(before_escape, vim.fn.maparg("<Esc>", "n", false, true))
      eq(false, tour.move(1))
    end)
  end)

  it("controls apply only in the tour editor, not another view of the same buffer", function()
    fixture(function(result)
      local editor = vim.api.nvim_get_current_win()
      local previous = vim.fn.maparg("<Right>", "n", false, true)
      vim.cmd("vsplit")
      local other = vim.api.nvim_get_current_win()
      vim.api.nvim_set_current_win(editor)
      tour.open(result)
      vim.api.nvim_set_current_win(other)
      eq(previous, vim.fn.maparg("<Right>", "n", false, true))
      vim.api.nvim_set_current_win(editor)
      press("<Right>")
      eq(result.locations[2].path, vim.api.nvim_buf_get_name(0))
    end)
  end)

  it("new mappings assigned during a tour survive its cleanup", function()
    fixture(function(result)
      tour.open(result)
      vim.keymap.set("n", "<Right>", "w", { buffer = 0, desc = "User's new mapping" })
      tour.close()
      eq("w", vim.fn.maparg("<Right>", "n", false, true).rhs)
    end)
  end)

  it("arrow navigation retains unsaved source edits without adding comments or saving files", function()
    fixture(function(result)
      local buffer = vim.api.nvim_get_current_buf()
      local lines = { "entry", "unsaved_call()", "continue()", "done" }
      vim.api.nvim_buf_set_lines(buffer, 0, -1, false, lines)
      local panel = tour.open(result)
      truthy(text(panel):find("Location may be stale", 1, true))
      press("<Right>")
      press("<Left>")
      tour.close()
      eq(lines, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
      eq(true, vim.bo[buffer].modified)
      eq({ "entry", "call()", "continue()", "done" }, vim.fn.readfile(result.locations[1].path))
    end)
  end)

  it("closing either tour window releases its controls and highlight", function()
    for _, target in ipairs({ "panel", "source" }) do
      fixture(function(result)
        local source, buffer = vim.api.nvim_get_current_win(), vim.api.nvim_get_current_buf()
        vim.keymap.set("n", "<Right>", "w", { buffer = buffer, desc = "Original right" })
        local previous = vim.fn.maparg("<Right>", "n", false, true)
        local panel = tour.open(result)
        vim.api.nvim_win_close(target == "source" and source or panel_window(panel), true)
        eq(false, tour.move(1))
        wait_for(function() return not vim.api.nvim_buf_is_valid(panel) end)
        eq({}, marks(buffer))
        vim.api.nvim_buf_call(buffer, function()
          eq(previous, vim.fn.maparg("<Right>", "n", false, true))
        end)
      end)
    end
  end)

  it("wiping the explanation buffer exits without leaving controls on the source", function()
    fixture(function(result)
      local source = vim.api.nvim_get_current_buf()
      local previous = vim.fn.maparg("<Right>", "n", false, true)
      local panel = tour.open(result)
      vim.api.nvim_buf_delete(panel, { force = true })
      wait_for(function() return not tour.move(0) end)
      eq({}, marks(source))
      eq(previous, vim.fn.maparg("<Right>", "n", false, true))
    end)
  end)

  it("wiping the source buffer stops the tour without leaving an explanation panel", function()
    fixture(function(result)
      local source = vim.api.nvim_get_current_buf()
      vim.keymap.set("n", "<Right>", "w", { buffer = source })
      local panel = tour.open(result)
      vim.api.nvim_buf_delete(source, { force = true })
      eq(false, tour.move(1))
      wait_for(function() return not vim.api.nvim_buf_is_valid(panel) end)
    end)
  end)

  it("independent tabs keep their own tour steps and arrow controls", function()
    fixture(function(result)
      local first_tab = vim.api.nvim_get_current_tabpage()
      local first_panel = tour.open(result)
      vim.cmd("tabnew")
      local second_tab = vim.api.nvim_get_current_tabpage()
      local ok, error_message = xpcall(function()
        local second_panel = tour.open(vim.deepcopy(result))
        press("<Right>")
        truthy(text(second_panel):find("Step 2 of 3", 1, true))
        vim.api.nvim_set_current_tabpage(first_tab)
        truthy(text(first_panel):find("Step 1 of 3", 1, true))
        press("<Right>")
        eq(result.locations[2].path, vim.api.nvim_buf_get_name(0))
        truthy(text(first_panel):find("Step 2 of 3", 1, true))
        tour.close()
        eq(true, vim.api.nvim_buf_is_valid(second_panel))
        vim.api.nvim_set_current_tabpage(second_tab)
        press("<Right>")
        truthy(text(second_panel):find("Step 3 of 3", 1, true))
      end, debug.traceback)
      vim.api.nvim_set_current_tabpage(second_tab)
      tour.close()
      vim.cmd("tabclose!")
      assert(ok, error_message)
    end)
  end)

  it("bounds and unavailable files leave the current stop intact", function()
    fixture(function(result, notices)
      local panel = tour.open(result)
      local before = text(panel)
      press("<Left>")
      eq("Start of tour", notices[1])
      result.locations[2].path = result.cwd .. "/missing.lua"
      press("<Right>")
      eq(result.locations[1].path, vim.api.nvim_buf_get_name(0))
      eq(before, text(panel))
      eq("Location is unavailable in the working tree: " .. result.locations[2].path, notices[2])
      eq({ 2, 0 }, vim.api.nvim_win_get_cursor(0))
      tour.open(result, 3)
      press("<Right>")
      eq("End of tour", notices[3])
      truthy(text(panel):find("Step 3 of 3", 1, true))
    end)
  end)

  it("reopening resumes the previous stop while another tour starts its own first stop", function()
    fixture(function(result)
      local old_panel = tour.open(result)
      press("<Right>")
      tour.close()
      local panel = tour.open(result)
      eq(false, vim.api.nvim_buf_is_valid(old_panel))
      truthy(text(panel):find("Step 2 of 3", 1, true))
      local other = vim.deepcopy(result)
      other.position = nil
      other.locations[1].notes = "A different tour's first step"
      local next_panel = tour.open(other)
      eq(false, vim.api.nvim_buf_is_valid(panel))
      truthy(text(next_panel):find(other.locations[1].notes, 1, true))
      eq(result.locations[1].path, vim.api.nvim_buf_get_name(0))
    end)
  end)

  it("a tour without locations shows its scope question instead of entering tour mode", function()
    fixture(function(result)
      result.locations = {}
      result.report = "Tour needs scope: which flow?"
      local before = vim.fn.maparg("<Right>", "n", false, true)
      local panel = tour.open(result)
      truthy(text(panel):find(result.report, 1, true))
      eq(false, tour.move(1))
      eq(before, vim.fn.maparg("<Right>", "n", false, true))
    end)
  end)
end)
