local vimgentic = require("vimgentic")
local oneshot = require("vimgentic.ops.oneshot")
local prompt_ui = require("vimgentic.ui.prompt")
local util = require("vimgentic.util")

local function fixture(callback)
  local original_run, original_open, original_notify = oneshot.run, prompt_ui.open, util.notify
  local buffer = vim.api.nvim_create_buf(true, false)
  vim.api.nvim_set_current_buf(buffer)
  vim.api.nvim_buf_set_lines(buffer, 0, -1, false, { "before", "return price", "after" })
  local state = { requests = {}, notices = {} }
  oneshot.run = function(options) table.insert(state.requests, options) end
  prompt_ui.open = function(options) state.prompt = options end
  util.notify = function(message) table.insert(state.notices, message) end
  local ok, error_message = xpcall(function() callback(buffer, state) end, debug.traceback)
  for _, request in ipairs(state.requests) do
    request.status:stop()
    request.on_finish()
  end
  if state.prompt then state.prompt.on_cancel() end
  if vim.api.nvim_buf_is_valid(buffer) then vim.api.nvim_buf_delete(buffer, { force = true }) end
  oneshot.run, prompt_ui.open, util.notify = original_run, original_open, original_notify
  assert(ok, error_message)
end

local function reply(request, text)
  request.on_result(text)
  request.status:stop()
  request.on_finish()
end

local function accept()
  vimgentic.visual_preview()
  eq("diff", vim.bo.filetype)
  vim.fn.maparg("<CR>", "n", false, true).callback()
end

describe("vimgentic.visual", function()
  it("requests a read-only replacement and waits for acceptance before changing the live buffer", function()
    fixture(function(buffer, state)
      local editor_window = vim.api.nvim_get_current_win()
      vimgentic.visual({ first = 2, last = 2, prompt = "Use total instead of price" })
      eq(1, #state.requests)
      local request = state.requests[1]
      eq({ "read", "grep", "find", "ls" }, request.tools)
      truthy(request.prompt:find("Selection:\nreturn price", 1, true))
      truthy(request.prompt:find("Selected lines: 2-2", 1, true))
      reply(request, "```lua\nreturn total\n```")
      eq(editor_window, vim.api.nvim_get_current_win())
      eq({ "before", "return price", "after" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
      accept()
      eq({ "before", "return total", "after" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
      eq(editor_window, vim.api.nvim_get_current_win())
    end)
  end)

  it("uses the command's line range instead of old visual marks", function()
    fixture(function(buffer, state)
      local root = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h:h")
      dofile(root .. "/plugin/vimgentic.lua")
      vim.api.nvim_buf_set_mark(buffer, "<", 1, 0, {})
      vim.api.nvim_buf_set_mark(buffer, ">", 1, 0, {})
      vim.cmd("2,3VimgenticVisual Use total")
      eq({ 2, 3 }, state.requests[1].metadata.range)
      truthy(state.requests[1].prompt:find("Selection:\nreturn price\nafter", 1, true))
      reply(state.requests[1], "return total")
      vim.cmd("VimgenticVisualPreview")
      eq("diff", vim.bo.filetype)
      vim.fn.maparg("<CR>", "n", false, true).callback()
      eq({ "before", "return total" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    end)
  end)

  it("cancels the prompt without starting a request or leaving a preview", function()
    fixture(function(buffer, state)
      vimgentic.visual({ first = 2, last = 2 })
      state.prompt.on_cancel()
      vimgentic.visual_preview()
      eq({}, state.requests)
      eq({ "No visual replacement is ready in this buffer" }, state.notices)
      eq(buffer, vim.api.nvim_get_current_buf())
      eq({ "before", "return price", "after" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    end)
  end)

  it("rejects a stale selection before it submits the prompt", function()
    fixture(function(buffer, state)
      vimgentic.visual({ first = 2, last = 2 })
      vim.api.nvim_buf_set_text(buffer, 1, 7, 1, 12, { "discount" })
      state.prompt.on_submit("Use total")
      eq({}, state.requests)
      eq({ "The selected text changed; no text was replaced. Request a new replacement." }, state.notices)
      eq({ "before", "return discount", "after" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    end)
  end)

  it("ignores an older reply after a new request replaces it in the same buffer", function()
    fixture(function(buffer, state)
      vimgentic.visual({ first = 2, last = 2, prompt = "Use tax" })
      vimgentic.visual({ first = 2, last = 2, prompt = "Use total" })
      reply(state.requests[1], "return tax")
      reply(state.requests[2], "return total")
      eq({ "before", "return price", "after" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
      accept()
      eq({ "before", "return total", "after" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    end)
  end)

  it("ignores a reply after the source buffer is deleted", function()
    fixture(function(buffer, state)
      vimgentic.visual({ first = 2, last = 2, prompt = "Use total" })
      vim.api.nvim_buf_delete(buffer, { force = true })
      local current_buffer = vim.api.nvim_get_current_buf()
      reply(state.requests[1], "return total")
      eq(current_buffer, vim.api.nvim_get_current_buf())
      eq({}, state.notices)
    end)
  end)

  it("releases a request that finishes without a replacement", function()
    fixture(function(buffer, state)
      vimgentic.visual({ first = 2, last = 2, prompt = "Use total" })
      state.requests[1].on_finish()
      vimgentic.visual_preview()
      eq({ "No visual replacement is ready in this buffer" }, state.notices)
      eq({ "before", "return price", "after" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    end)
  end)

  it("rejects an empty reply without deleting the selected code", function()
    fixture(function(buffer, state)
      vimgentic.visual({ first = 2, last = 2, prompt = "Use total" })
      reply(state.requests[1], "  \n")
      vimgentic.visual_preview()
      eq({ "vimgentic visual returned an empty replacement", "No visual replacement is ready in this buffer" }, state.notices)
      eq({ "before", "return price", "after" }, vim.api.nvim_buf_get_lines(buffer, 0, -1, false))
    end)
  end)
end)
